name: module_13
description: "A Favorite Places app with camera and location features"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  location: ^5.0.3
  google_maps_flutter: ^2.5.3
  path_provider: ^2.1.2
  path: ^1.8.3
  sqflite: ^2.3.2
  uuid: ^4.3.3
  flutter_riverpod: ^2.5.1
  http: ^1.2.0
  firebase_core: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
