// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb-GEOEyq44ey2ptKdiPDFMBHUDEhTgpU',
    appId: '1:17091609090:web:865b159961508f12e09d1b',
    messagingSenderId: '17091609090',
    projectId: 'flutter-course-application',
    authDomain: 'flutter-course-application.firebaseapp.com',
    storageBucket: 'flutter-course-application.firebasestorage.app',
    measurementId: 'G-BYF0R5P1H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxgQWyro4aXK3J_JPt9kBUqTojOmxLVUE',
    appId: '1:17091609090:android:13090f9af2c3b13de09d1b',
    messagingSenderId: '17091609090',
    projectId: 'flutter-course-application',
    storageBucket: 'flutter-course-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTbVz-1Ofb-tm_dMS8hsvGWORYp6451ts',
    appId: '1:17091609090:ios:5e3966600f5c19f6e09d1b',
    messagingSenderId: '17091609090',
    projectId: 'flutter-course-application',
    storageBucket: 'flutter-course-application.firebasestorage.app',
    iosBundleId: 'com.example.module13',
  );
}
